```{r message=FALSE, warning=FALSE}
ca_test <- data.table::fread("/Users/oliviashi/Documents/MASTER_RESEARCH/Covid19Canada/timeseries_prov/testing_timeseries_prov.csv")

ca_cases <- data.table::fread("/Users/oliviashi/Documents/MASTER_RESEARCH/Covid19Canada/timeseries_prov/cases_timeseries_prov.csv")

ca_mortality <- data.table::fread("/Users/oliviashi/Documents/MASTER_RESEARCH/Covid19Canada/timeseries_prov/mortality_timeseries_prov.csv")


ca_cases$date<-as.Date(ca_cases$date_report,format="%d-%m-%Y", tryFormats= "%Y-%m-%d") 
ca_test$date<-as.Date(ca_test$date_testing,format="%d-%m-%Y", tryFormats= "%Y-%m-%d")

n=length(ca_cases$province)
# ca_cases%>% filter(province=="Quebec")

for(i in 3:n){
  if((!is.finite(ca_cases$cases[i]))&(ca_cases$province[i]==ca_cases$province[i-1])){
   ca_cases$cases[i]<-ca_cases$cases[i-1]
  }
  # if((ca_cases$cases[i]==0)&(ca_cases$province[i]==ca_cases$province[i-1])){
  #  ca_cases$cases[i]<-ca_cases$cases[i-1]#+abs(ceiling(rnorm(1,0,1)))
  # }
  if((ca_cases$cases[i]<1000)&(ca_cases$cases[i-1]>2000)&(ca_cases$province[i]=="Ontario")){
   ca_cases$cases[i]<-ca_cases$cases[i-1]+(ceiling(rnorm(1,0,100)))
  }
  if((ca_cases$cases[i]<50)&(ca_cases$cases[i-1]>500)&(ca_cases$province[i]==ca_cases$province[i-1])){
   ca_cases$cases[i]<-ca_cases$cases[i-1]+(ceiling(rnorm(1,0,10)))
  }
}

for(i in 3:n){
  if(((ca_cases$cases[i]-ca_cases$cases[i-1])>(ca_cases$cases[i-1]*1.4+500))&(ca_cases$province[i]==ca_cases$province[i-1])){
   ca_cases$cases[i]<-(ca_cases$cases[i-1]+ca_cases$cases[i]*0.5)/2
  }
}


```



```{r}
# ca_cases$casesMA<-
ca_test$testingMA<-rollmean(ca_test$testing,3,fill=NA)
ca_cases$casesMA<-ceiling(rollmean(ca_cases$cases,3,fill=NA))
# for(i in 3:n){
#   if(is.finite(ca_test$testingMA[i])){
#     a<-3
#   }else{ca_test$testingMA[i]<-ca_test$testingMA[i-1]}
# }

d<-join(ca_cases,ca_test,by=c("date","province"),type="left",match="first")
myfunc <- function(df,x,y){df[df$date >= x & df$date <= y,]}
d <- myfunc(d,as.Date("2020-04-01"),as.Date("2021-12-01"))
n=length(d$province)
data_po <- data.frame(date=c(rep(NA,n)),positivity=c(rep(NA,n)),province=c(rep(NA,n)))
data_po$date <- d$date
data_po$province <- d$province


for(i in 1:length(d$casesMA)){
  data_po$positivity[i] <-ifelse(d$casesMA[i]<d$testingMA[i],
                                 d$casesMA[i]/d$testingMA[i],
                                 d$casesMA[i-1]/d$testingMA[i-1])
  data_po$positivity[i]<-max(0,data_po$positivity[i])}


data<-join(d,data_po,by=c("date","province"),type="left",match="first")

data$positivityMA  <- rollmean(data$positivity,14,fill=NA)
data<-data%>%filter(province!="NWT" &province!="Repatriated"&province!="Nunavut"&province!="Yukon")
date_start='2020-04-01'
date_end='2021-12-01'
data$province[data$province=="Quebec"]<-"Québec"

data$province[data$province=="NL"]<-"Newfoundland and Labrador"
data$province[data$province=="PEI"]<-"Prince Edward Island"
data$province[data$province=="BC"]<-"British Columbia"
unique(data$province)
```


positivity_each_province
```{r}
positivity_each_province<-ggplot(data=data,aes(date)) +
  geom_line(aes(y = positivityMA, group=province, colour = province)) +
  scale_x_date(breaks = "2 months", date_labels = "%b/%y")+
  theme(aspect.ratio=0.7,
          legend.title =element_blank(),
          axis.title.x=element_blank())+
  scale_colour_brewer(palette = "Paired")+
  ylab("Positivity")

positivity_each_province
ggsave("./LatexImages/positivity_each_province.png",positivity_each_province,scale=1)
knitr::plot_crop("./LatexImages/positivity_each_province.png")

```

reported_each_province_raw
```{r}
reported_each_province_raw<-ggplot(data=data,aes(date)) +
      geom_point(aes(y = cases, colour = "Reported cases"),cex=0.2) + 
  facet_wrap(~province,ncol=2,scales="free_y",shrink=T)+
  theme(axis.text=element_text(size=6),
        axis.title=element_text(size=6),
        plot.margin = margin(0,0,0,0, "cm"),
        axis.text.x = element_text(angle=45, hjust = 1),
        legend.title =element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",axis.title.y=element_blank())+
  scale_x_date(breaks = "2 months", date_labels = "%b/%y",limits =
                 as.Date(c(date_start,date_end)))
  

reported_each_province_raw

ggsave("../LatexImages/reported_each_province_raw.png",reported_each_province_raw,height=6,width=6)
knitr::plot_crop("../LatexImages/reported_each_province_raw.png")

```


reported_each_province
```{r}
reported_each_province1<-ggplot(data=data,aes(date)) +
      geom_line(aes(y = casesMA, colour = "Reported cases"),cex=0.5) + 
  facet_wrap(~province,ncol=2,scales="free_y",shrink=T)+
  theme(axis.text=element_text(size=6),
        axis.title=element_text(size=6),
        plot.margin = margin(0,0,0,0, "cm"),
        axis.text.x = element_text(angle=45, hjust = 1),
        legend.title =element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",axis.title.y=element_blank())+
  scale_x_date(breaks = "2 months", date_labels = "%b/%y",limits =
                 as.Date(c(date_start,date_end)))
  
reported_each_province1
reported_each_province

# data%>%filter(province=="Québec")
ggsave("../LatexImages/reported_each_province.png",reported_each_province1,height=6,width=6)
knitr::plot_crop("../LatexImages/reported_each_province.png")

```



```{r}
ABBC<-ggplot(data=data[data$province=="BC"|data$province=="AB"],aes(date)) +
      geom_line(aes(y = cases, colour = "Reported cases")) + 
  facet_wrap(~province,scales="free_y")+
  theme(axis.text.x = element_text(angle=45, hjust = 1),
        legend.title =element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",axis.title.y=element_blank())+
  scale_x_date(date_labels = "%b/%y")
BC
MBNB<-ggplot(data=data[data$province=="MB"|data$province=="NB"],aes(date)) +
      geom_line(aes(y = casesMA, colour = "Reported cases")) + 
  facet_wrap(~province,scales="free_y")+
  theme(axis.text.x = element_text(angle=45, hjust = 1),
        legend.title =element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",axis.title.y=element_blank())+
  scale_x_date(date_labels = "%b/%y")

a1<-ggarrange(ABBC,MBNB,nrow=2)
a2<-ggarrange(ABBC,MBNB,nrow=2)
plot<-rbind(a1,a2)
plot


data <- data.frame(date=c(rep(NA,n)),tests=c(rep(NA,n)),cases=c(rep(NA,n)),province=c(rep(NA,n)))
data$date <- as.Date(ca_cases$date_report[1:n],'%d-%m-%Y')
data$province<-ca_test$province[1:n]
data$tests <- ca_test$testing[1:n]
data$cases <- ca_cases$cases[1:n]
data$deaths <- ca_mortality$deaths[1:n]
data_po <- data.frame(date=c(rep(NA,n)),positivity=c(rep(NA,n)))
data_po$positivity <- data$cases / data$tests
data_po$date <- data$date
data<-join(data,data_po,by="date",type="left",match="first")
data$positivityMA  <- rollmean(data$positivity,14,fill=NA)
myfunc <- function(df,x,y){df[df$date >= x & df$date <= y,]}
# data <- myfunc(data,as.Date("2020-04-01"),as.Date("2021-04-01"))  
findDayi <- function(x){res<-0
  for(i in 1:length(x)){res<-difftime(x,as.Date("2020-03-15"),units="days")}
  return(as.numeric(res))}
data$dayi<-findDayi(data$date)

for(i in 1:length(data$dayi)){
  data$prevalence[i] <- (1500 / (data$dayi[i] + 50)) * (data$positivity[i])^(0.5) + 2
  data$a[i] <- 1500 / (data$dayi[i] + 50)}

data$casesPR <- data$cases * data$prevalence
data$casesPR[1]<-0
for(i in 2:n){
  if(is.finite(data$casesPR[i])){
    a<-1
  }else{
    data$casesPR[i]<-data$casesPR[i-1]
  }
}
```

```{r}
ca_test
```


```{r}
ggplot(data=data,aes(date)) +
      geom_line(aes(y = positivity, group=province, colour = province)) +
  ggtitle("Posivity rate for each province in Canada")
```

```{r}
# Move to a new page
grid.newpage()
# Create layout : nrow = 2, ncol = 2
pushViewport(viewport(layout = grid.layout(3, 1)))

define_region <- function(row, col){
  viewport(layout.pos.row = row, layout.pos.col = col)
} 
# Arrange the plots
print(ABBC, vp=define_region(1, 1))
print(ABBC, vp = define_region(2, 1))
print(ABBC, vp = define_region(3, 1))

data$province[data$province=="Newfoundland and Labrador"]<-"NL"
data$province[data$province=="Prince Edward Island"]<-"PEI"
data$province[data$province=="British Columbia"]<-"BC"
data$province[data$province=="New Brunswick"]<-"NB"
data$province[data$province=="Alberta"]<-"AB"
data$province[data$province=="Nova Scotia"]<-"NS"
data$province[data$province=="Manitoba"]<-"MB"
data$province[data$province=="Saskatchewan"]<-"SK"
data$province[data$province=="Ontario"]<-"ON"
```



